#############################################################################
# Makefile for building: classwizard
# Generated by qmake (2.01a) (Qt 4.5.3) on: ?? 12? 22 09:57:28 2011
# Project:  classwizard.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile classwizard.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -march=mips3 -mplt -O3 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=mips3 -mplt -O3 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtTest -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtTest -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = classwizard.cpp \
		main.cpp \
		mainwindow.cpp \
		diskinfo.cpp \
		addpartdialog.cpp \
		partitonwizard.cpp \
		addrevert.cpp moc_classwizard.cpp \
		moc_mainwindow.cpp \
		moc_addpartdialog.cpp \
		moc_partitionwizard.cpp \
		moc_addrevert.cpp
OBJECTS       = classwizard.o \
		main.o \
		mainwindow.o \
		diskinfo.o \
		addpartdialog.o \
		partitonwizard.o \
		addrevert.o \
		moc_classwizard.o \
		moc_mainwindow.o \
		moc_addpartdialog.o \
		moc_partitionwizard.o \
		moc_addrevert.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		classwizard.pro
QMAKE_TARGET  = classwizard
DESTDIR       = 
TARGET        = classwizard

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: classwizard.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtTest.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile classwizard.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtTest.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile classwizard.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/classwizard1.0.0 || $(MKDIR) .tmp/classwizard1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/classwizard1.0.0/ && $(COPY_FILE) --parents classwizard.h mainwindow.h diskinfo.h addpartdialog.h partitionwizard.h addrevert.h architecture.h .tmp/classwizard1.0.0/ && $(COPY_FILE) --parents classwizard.cpp main.cpp mainwindow.cpp diskinfo.cpp addpartdialog.cpp partitonwizard.cpp addrevert.cpp .tmp/classwizard1.0.0/ && $(COPY_FILE) --parents gaea/trans/zh.ts gaea/trans/en.ts .tmp/classwizard1.0.0/ && (cd `dirname .tmp/classwizard1.0.0` && $(TAR) classwizard1.0.0.tar classwizard1.0.0 && $(COMPRESS) classwizard1.0.0.tar) && $(MOVE) `dirname .tmp/classwizard1.0.0`/classwizard1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/classwizard1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_classwizard.cpp moc_mainwindow.cpp moc_addpartdialog.cpp moc_partitionwizard.cpp moc_addrevert.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_classwizard.cpp moc_mainwindow.cpp moc_addpartdialog.cpp moc_partitionwizard.cpp moc_addrevert.cpp
moc_classwizard.cpp: partitionwizard.h \
		diskinfo.h \
		mainwindow.h \
		architecture.h \
		addpartdialog.h \
		addrevert.h \
		classwizard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) classwizard.h -o moc_classwizard.cpp

moc_mainwindow.cpp: architecture.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_addpartdialog.cpp: architecture.h \
		addpartdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) addpartdialog.h -o moc_addpartdialog.cpp

moc_partitionwizard.cpp: diskinfo.h \
		mainwindow.h \
		architecture.h \
		addpartdialog.h \
		addrevert.h \
		partitionwizard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) partitionwizard.h -o moc_partitionwizard.cpp

moc_addrevert.cpp: addrevert.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) addrevert.h -o moc_addrevert.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

classwizard.o: classwizard.cpp classwizard.h \
		partitionwizard.h \
		diskinfo.h \
		mainwindow.h \
		architecture.h \
		addpartdialog.h \
		addrevert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classwizard.o classwizard.cpp

main.o: main.cpp classwizard.h \
		partitionwizard.h \
		diskinfo.h \
		mainwindow.h \
		architecture.h \
		addpartdialog.h \
		addrevert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		architecture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

diskinfo.o: diskinfo.cpp diskinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskinfo.o diskinfo.cpp

addpartdialog.o: addpartdialog.cpp addpartdialog.h \
		architecture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addpartdialog.o addpartdialog.cpp

partitonwizard.o: partitonwizard.cpp partitionwizard.h \
		diskinfo.h \
		mainwindow.h \
		architecture.h \
		addpartdialog.h \
		addrevert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o partitonwizard.o partitonwizard.cpp

addrevert.o: addrevert.cpp diskinfo.h \
		addrevert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addrevert.o addrevert.cpp

moc_classwizard.o: moc_classwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_classwizard.o moc_classwizard.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_addpartdialog.o: moc_addpartdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addpartdialog.o moc_addpartdialog.cpp

moc_partitionwizard.o: moc_partitionwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_partitionwizard.o moc_partitionwizard.cpp

moc_addrevert.o: moc_addrevert.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addrevert.o moc_addrevert.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/etc/ || $(MKDIR) $(INSTALL_ROOT)/etc/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-strip "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/etc/ || $(MKDIR) $(INSTALL_ROOT)/etc/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-strip "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install:  install_target install_target  FORCE

uninstall: uninstall_target uninstall_target   FORCE

FORCE:

