Document: classwizard
Title: Debian classwizard Manual
Author: <insert document author here>
Abstract: This manual describes what classwizard is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/classwizard/classwizard.sgml.gz

Format: postscript
Files: /usr/share/doc/classwizard/classwizard.ps.gz

Format: text
Files: /usr/share/doc/classwizard/classwizard.text.gz

Format: HTML
Index: /usr/share/doc/classwizard/html/index.html
Files: /usr/share/doc/classwizard/html/*.html
